eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

batch:
  filesScan:
    path: src/test/resources/inboundFiles
    pattern: ^[^~].*\\.xlsx?$

spring:
  rabbitmq:
    hostname: localhost
    username: cedric
    password: sada123

logging:
  level:
    root: INFO
    org.springframework: INFO
      #aop: DEBUG
      #dao: DEBUG
      #orm: DEBUG
      #amqp: DEBUG
      #data: DEBUG
      #transaction: DEBUG
    org.axonframework: INFO
    com.sada.batch: INFO
  file: ./logs/sinistres-batch.log
