eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

spring:
  application:
    exchange: sinistres.events.fanoutExchange
    queue: sinistres.events.queue
    databaseName: sinitres-batch
    eventsCollectionName: sinistresEvents
    snapshotCollectionName: sinistresSnapshots
  rabbitmq:
    hostname: localhost
    username: cedric
    password: sada123
    port: 5672
  data:
    mongodb:
      database: ${spring.application.databaseName}
      host: localhost
      port: 27017

logging:
  level:
    root: INFO
    org.springframework: INFO
      #aop: DEBUG
      #dao: DEBUG
      #orm: DEBUG
      #amqp: DEBUG
      #data: DEBUG
      #transaction: DEBUG
    org.axonframework: INFO
    com.sada.command: DEBUG
  file: ./logs/sinistres-command.log
